### ISSUE TITLE
Out Of memory

### ISSUE THREAD

**Issue by vermavijay** [ferortega/cf4j#3]
After increasing the heap size to 2.5GB, the library is not able to execute the Movielens 10M dataset (-Xms2048M -Xmx2560M).
Please consider this issue.

**Comment by ferortega** [comment]
Which recommendation methods are you ussing?

Test users and items porcent?

**Comment by ferortega** [comment]
I am on mu vacations. Can you remind me next week?

You can try to drecrease the % of test users.

**Comment by ferortega** [comment]
Did you try to reduce the % of test users? CF4J has not beed designed to save memory, it duplicates a lot of information in order to facilitate the experiment encoding.

**Comment by vermavijay** [comment]
Thanks for your suggestions, it works for Movielens 10M dataset after reducing the % of test users to 0.05 (i.e. 5%) & keeping the % of test items to 0.20 (i.e. 20%).

Dear sir, can you plz elaborate that why there are 2 testing parameters (% of test users & test items) are specified? What will happen if we specify only one of them?

**Comment by ferortega** [comment]
You do not have a constructor to specify only one parameter. You must specify both parameters always because both are required. The % of test users specify the users used to validate you RS and the % of test items will define the % of items rated by test users that will be used for the validation.

I close this issue as solved.

**Comment by vermavijay** [comment]
Thanks
